apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-bot
  labels:
    app: slack-bot
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: slack-bot
  template:
    metadata:
      labels:
        app: slack-bot
    spec:
      containers:
      - name: slack-bot
        image: alajfit/ketonab:slack-bot-8
        imagePullPolicy: Always
        resources:
{{ .Values.resources | toYaml | indent 10}}
      imagePullSecrets:
      - name: regcred
