---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: slack-bot
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://github.com/alajfit/app.deployments.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: slack-bot
  description: "Applications that are used for fast development"
